// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/doc": {
            "get": {
                "description": "Returns the generated Swagger document for this service.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "documentation"
                ],
                "summary": "Get OpenAPI document",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/estimation/flow": {
            "post": {
                "description": "Returns cost estimations for the provided list of flow IDs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "estimations"
                ],
                "summary": "Get flow cost estimations",
                "parameters": [
                    {
                        "description": "Flow IDs",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Estimation"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/estimation/flow/{id}": {
            "get": {
                "description": "Returns the cost estimation for a single flow ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "estimations"
                ],
                "summary": "Get flow cost estimation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Flow ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Estimation"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/estimation/import": {
            "post": {
                "description": "Returns cost estimations for the provided list of import type IDs.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "estimations"
                ],
                "summary": "Get import cost estimations",
                "parameters": [
                    {
                        "description": "Import type IDs",
                        "name": "ids",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "string"
                            }
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/model.Estimation"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/estimation/import/{id}": {
            "get": {
                "description": "Returns the cost estimation for a single import type ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "estimations"
                ],
                "summary": "Get import cost estimation",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Import type ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.Estimation"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns a successful status when the API is ready to serve requests.",
                "tags": [
                    "health"
                ],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/tree": {
            "get": {
                "description": "Returns the aggregated cost tree across all supported cost types for the current user or a delegated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "costs"
                ],
                "summary": "Get aggregated cost tree",
                "parameters": [
                    {
                        "type": "boolean",
                        "description": "Skip estimation values in the response",
                        "name": "skip_estimation",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time in RFC3339 format",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time in RFC3339 format",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User ID to query as admin",
                        "name": "for_user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CostTree"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tree/{costType}": {
            "get": {
                "description": "Returns the detailed cost tree for one cost type for the current user or a delegated user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "costs"
                ],
                "summary": "Get cost tree for a single cost type",
                "parameters": [
                    {
                        "enum": [
                            "analytics",
                            "imports",
                            "API Calls",
                            "Exports",
                            "Devices",
                            "process",
                            "MQTTExports",
                            "Reporting"
                        ],
                        "type": "string",
                        "description": "Cost type",
                        "name": "costType",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "Skip estimation values in the response",
                        "name": "skip_estimation",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Start time in RFC3339 format",
                        "name": "start",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End time in RFC3339 format",
                        "name": "end",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "User ID to query as admin",
                        "name": "for_user",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/model.CostWithChildren"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.CostEntry": {
            "type": "object",
            "properties": {
                "cpu": {
                    "type": "number"
                },
                "ram": {
                    "type": "number"
                },
                "requestedDatapoints": {
                    "type": "integer"
                },
                "requests": {
                    "type": "number"
                },
                "storage": {
                    "type": "number"
                }
            }
        },
        "model.CostTree": {
            "type": "object",
            "additionalProperties": {
                "$ref": "#/definitions/model.CostWithChildren"
            }
        },
        "model.CostWithChildren": {
            "type": "object",
            "properties": {
                "children": {
                    "type": "object",
                    "additionalProperties": {
                        "$ref": "#/definitions/model.CostWithChildren"
                    }
                },
                "estimation_month": {
                    "$ref": "#/definitions/model.CostEntry"
                },
                "month": {
                    "$ref": "#/definitions/model.CostEntry"
                }
            }
        },
        "model.Estimation": {
            "type": "object",
            "properties": {
                "max": {
                    "type": "number"
                },
                "mean": {
                    "type": "number"
                },
                "median": {
                    "type": "number"
                },
                "min": {
                    "type": "number"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Cost Calculator API",
	Description:      "Provides cost overview and estimations for imports and flows.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
